### ISSUE TITLE
Unary minus for SafeUnsigned types

### ISSUE THREAD

**Issue by sostock** [JeffreySarnoff/SaferIntegers.jl#10]
Unary minus is not overflow-aware for `SafeUnsigned` types:
```julia
julia> -SafeUInt(1)
18446744073709551615
```
If this is the desired behavior, it would be good to mention it in the documentation.

**Comment by JeffreySarnoff** [comment]
no, I agree that should be trapped.  thank you.  fixing it now.

**Comment by JeffreySarnoff** [comment]
fixed in master, reregistered, merge pending
(that was a good find, and it also caught a gap in the handling of `~`)

**Comment by sostock** [comment]
Thanks for the quick fixes!

**Comment by JeffreySarnoff** [comment]
@sostock fyi, the current, just merged, version has both this and the type conversion corrections.
