### ISSUE TITLE
Using SaferIntegers for "python-like" ints

### ISSUE THREAD

**Issue by David-Berghaus** [JeffreySarnoff/SaferIntegers.jl#15]
Hi Jeffrey,

I am working on a project where most arithmetic can be performed with 64-bit integers, however it rarely happens that arbitrary precision integers have to be used. Therefore using only Int64 is not possible, while using only BigInts is not efficient.
I am hence trying to implement a hybrid-type (similar to what python3 does) where, if possible, Int64 are used, otherwise BigInts are applied. To detect overflows, I used your "SafeIntegers" package.

Here is my first (naive and unoptimized) implementation:
```
using SaferIntegers

#These functions are missing in SaferIntegers...
Base.:*(m1::BigInt, m2::SafeInt) = m1*Int(m2)
Base.:*(m1::SafeInt, m2::BigInt) = Int(m1)*m2
Base.:+(m1::BigInt, m2::SafeInt) = m1+Int(m2)
Base.:+(m1::SafeInt, m2::BigInt) = Int(m1)+m2
Base.:-(m1::BigInt, m2::SafeInt) = m1-Int(m2)
Base.:-(m1::SafeInt, m2::BigInt) = Int(m1)-m2

const int_limit = typemax(Int)
struct ZZ{T<:Integer} <: Integer
    val::T
    ZZ{BigInt}(val::BigInt) = abs(val) < int_limit ? ZZ{SafeInt}(SafeInt(val)) : new(val)
    ZZ{Int}(val::Int) = ZZ{SafeInt}(SafeInt(val))
    ZZ{SafeInt}(val::SafeInt) = new(val)
end

ZZ(val::BigInt) = ZZ{BigInt}(val)
ZZ(val::Int) = ZZ{Int}(val)
ZZ(val::SafeInt) = ZZ{SafeInt}(val)

Base.show(io::IO, ::MIME"text/plain", m::ZZ{T}) where T <: Integer = print(io, m.val)

Base.:*(m1::ZZ{BigInt}, m2::ZZ{BigInt}) = ZZ(m1.val*m2.val)
Base.:*(m1::ZZ{BigInt}, m2::ZZ{SafeInt}) = ZZ(m1.val*m2.val)
Base.:*(m1::ZZ{SafeInt}, m2::ZZ{BigInt}) = ZZ(m1.val*m2.val)
Base.:*(m1::ZZ{SafeInt}, m2::ZZ{SafeInt}) = ZZ(try m1.val*m2.val catch; BigInt(m1.val)*m2.val end)
Base.:*(m1::ZZ{SafeInt}, m2::Int) = ZZ(try m1.val*m2 catch; BigInt(m1.val)*m2 end)
Base.:*(m2::Int, m1::ZZ{SafeInt}) = ZZ(try m1.val*m2 catch; BigInt(m1.val)*m2 end)
Base.:*(m1::ZZ{SafeInt}, m2::BigInt) = ZZ(m1.val*m2)
Base.:*(m2::BigInt, m1::ZZ{SafeInt}) = ZZ(m1.val*m2)
Base.:*(m1::ZZ{BigInt}, m2::Int) = ZZ(m1.val*m2)
Base.:*(m2::Int, m1::ZZ{BigInt}) = ZZ(m1.val*m2)
Base.:*(m1::ZZ{BigInt}, m2::BigInt) = ZZ(m1.val*m2)
Base.:*(m2::BigInt, m1::ZZ{BigInt}) = ZZ(m1.val*m2)

Base.:+(m1::ZZ{BigInt}, m2::ZZ{BigInt}) = ZZ(m1.val+m2.val)
Base.:+(m1::ZZ{BigInt}, m2::ZZ{SafeInt}) = ZZ(m1.val+m2.val)
Base.:+(m1::ZZ{SafeInt}, m2::ZZ{BigInt}) = ZZ(m1.val+m2.val)
Base.:+(m1::ZZ{SafeInt}, m2::ZZ{SafeInt}) = ZZ(try m1.val+m2.val catch; BigInt(m1.val)+m2.val end)
Base.:+(m1::ZZ{SafeInt}, m2::Int) = ZZ(try m1.val+m2 catch; BigInt(m1.val)+m2 end)
Base.:+(m2::Int, m1::ZZ{SafeInt}) = ZZ(try m1.val+m2 catch; BigInt(m1.val)+m2 end)
Base.:+(m1::ZZ{SafeInt}, m2::BigInt) = ZZ(m1.val+m2)
Base.:+(m2::BigInt, m1::ZZ{SafeInt}) = ZZ(m1.val+m2)
Base.:+(m1::ZZ{BigInt}, m2::Int) = ZZ(m1.val+m2)
Base.:+(m2::Int, m1::ZZ{BigInt}) = ZZ(m1.val+m2)
Base.:+(m1::ZZ{BigInt}, m2::BigInt) = ZZ(m1.val+m2)
Base.:+(m2::BigInt, m1::ZZ{BigInt}) = ZZ(m1.val+m2)

Base.:-(m1::ZZ{BigInt}, m2::ZZ{BigInt}) = ZZ(m1.val-m2.val)
Base.:-(m1::ZZ{BigInt}, m2::ZZ{SafeInt}) = ZZ(m1.val-m2.val)
Base.:-(m1::ZZ{SafeInt}, m2::ZZ{BigInt}) = ZZ(m1.val-m2.val)
Base.:-(m1::ZZ{SafeInt}, m2::ZZ{SafeInt}) = ZZ(try m1.val-m2.val catch; BigInt(m1.val)-m2.val end)
Base.:-(m1::ZZ{SafeInt}, m2::Int) = ZZ(try m1.val-m2 catch; BigInt(m1.val)-m2 end)
Base.:-(m2::Int, m1::ZZ{SafeInt}) = ZZ(try m2-m1.val catch; m2-BigInt(m1.val) end)
Base.:-(m1::ZZ{SafeInt}, m2::BigInt) = ZZ(m1.val-m2)
Base.:-(m2::BigInt, m1::ZZ{SafeInt}) = ZZ(m2-m1.val)
Base.:-(m1::ZZ{BigInt}, m2::Int) = ZZ(m1.val-m2)
Base.:-(m2::Int, m1::ZZ{BigInt}) = ZZ(m2-m1.val)
Base.:-(m1::ZZ{BigInt}, m2::BigInt) = ZZ(m1.val-m2)
Base.:-(m2::BigInt, m1::ZZ{BigInt}) = ZZ(m2-m1.val)

function test_int()
    tmp = 0
    for i = 1:10^8
        tmp += i
    end
    return tmp
end

function test_safe_int()
    tmp = SafeInt(0)
    for i = 1:10^8
        tmp += i
    end
    return tmp
end

function test_ZZ_int()
    tmp = ZZ(0)
    for i = 1:10^8
        tmp += i
    end
    return tmp
end

function test_big_int()
    tmp = BigInt(0)
    for i = 1:10^8
        tmp += i
    end
    return tmp
end
```
With this implementation one can do things like:
```
julia> ZZ(int_limit)*ZZ(int_limit)
85070591730234615847396907784232501249
```
Here are some benchmark results (inside the 64-bit range):
```
julia> @btime test_int()
  1.099 ns (0 allocations: 0 bytes)
5000000050000000
julia> @btime test_safe_int()
  40.569 ms (0 allocations: 0 bytes)
5000000050000000
julia> @btime test_ZZ_int()
  3.306 s (0 allocations: 0 bytes)
5000000050000000
julia> @btime test_big_int()
  37.735 s (500000002 allocations: 8.20 GiB)
5000000050000000
```
As one can see, using ZZ is already an improvement over BigInts for this application, however one is still far away from the performance of SaferIntegers, although one never had to work with BigInts.
Do you see some ways to improve this code? One could try to inline some functions and perhaps my try/catch approach for detecting overflows is also very inefficient...

Best,
David

**Comment by JeffreySarnoff** [comment]
One thing to do would be to use `Int128`, `SafeInt128` before jumping to `BigInt`.
Also, rather than `Int`, `SafeInt` use `Int64`, `SafeInt64`, so it works well on all platforms.

**Comment by JeffreySarnoff** [comment]
As you thought, the current implementation of try-catch is quite inefficient.  How large do your integers get? How often?

**Comment by David-Berghaus** [comment]
Thank you for your suggestion for 128bit integers. I currently assume that I will not exceed the 128bit range therefore I can probably get rid of the BigInts completely. 

I have not performed any statistical tests on the size of the integers, but, based on the results that I get, I would guess that only maybe 1% of the operations is beyond the 64bit range. Therefore the bound-check inside the constructor for BigInts does also not cause a bottleneck.

One way to avoid the try/catch approach would be to perform bound-checks in advance, for example by counting digits and hard-coding bounds to ensure that the operation will definitely not cause any overflows. This will of course create some overhead but is probably more "compiler-friendly" than using try/catch. Most integers are very small (and therefore not in danger of overflow) which means that it is more important to keep the bound-check fast instead of making it very conservative.

**Comment by JeffreySarnoff** [comment]
Try running your code just using SafeInt28.  If it does not error (overflow) and runs fast enough, you are done.

Jeffrey Sarnoff

**Comment by David-Berghaus** [comment]
Yes, I will try this, thank you for your help! 👍
