### ISSUE TITLE
Overflow not captured ?

### ISSUE THREAD

**Issue by Marlin-Na** [JeffreySarnoff/SaferIntegers.jl#16]
Hi I just started trying this package, but it seems not capturing overflow of `100^10`?

```
julia> SafeInt(100)^9
1000000000000000000

julia> SafeInt(100)^10
7766279631452241920

julia> SafeInt(100)^11
ERROR: OverflowError: 100^11
```

**Comment by JeffreySarnoff** [comment]
```
julia> using SaferIntegers

julia> SafeInt(10)^SafeInt(111)
ERROR: OverflowError: 10^111
Stacktrace:
 [1] ^(x::SafeInt64, y::SafeInt64)
   @ SaferIntegers ~\.julia\packages\SaferIntegers\lLDKG\src\pow.jl:45
 [2] top-level scope
   @ REPL[4]:1

julia> 10^SafeInt(111)
ERROR: OverflowError: 10^111
Stacktrace:
 [1] ^(x::SafeInt64, y::SafeInt64)
   @ SaferIntegers ~\.julia\packages\SaferIntegers\lLDKG\src\pow.jl:45
 [2] ^(x::Int64, y::SafeInt64)
   @ SaferIntegers ~\.julia\packages\SaferIntegers\lLDKG\src\pow.jl:71
 [3] top-level scope
   @ REPL[5]:1
```
oh my, how absurd is that .. missed a case in promotion -- THANK YOU!! on it :)

**Comment by JeffreySarnoff** [comment]
We, the SaferIntegers User Community, are grateful for your attention to detail.
I, the package author, am on the fix.  Thank you for the  bug report.

**Comment by JeffreySarnoff** [comment]
notes isolating the bug in these cases, equivalent after implicit promotion: 
`SafeInteger(b)^p, b^SafeInteger(p), SafeInteger(b)^SafeInteger(p)`
where 
`SafeInteger(x::Union{Signed,Unsigned}) = convert(SafeInteger, x)` 
 
The bug in `b^p` occurs when the power is `p == 10` and the base `b` small enough to dispatch through table lookup. The most prudent approach is to regenerate all of the powering tables using a dynamically adjusting validity check to trap and report any case where an incorrect outcome is reported -- presuming no such cases arise, the fix fixed it.

**Comment by JeffreySarnoff** [comment]
fixed
