### ISSUE TITLE
Just wanted to say THANKS!

### ISSUE THREAD

**Issue by nickeubank** [JeffreySarnoff/SaferIntegers.jl#2]
This package is amazing. Exactly [what i've wanted from Julia](https://discourse.julialang.org/t/a-plea-for-int-overflow-checking-as-the-default/3338). Thank you!

**Comment by JeffreySarnoff** [comment]
You are most welcome.  I appreciate the feedback.  

What is your opinion of including checked shifts (if you shift by more than the bitwidth, tthat would be caught)?

**Comment by nickeubank** [comment]
My inclination would be to say it's not necessary if it slows down other behaviors -- I think of int overflow checking as a tool that's most valuable for more naive users (I'm a social scientist, and most of my students have never heard of an int overflow and probably haven't been taught enough about how numbers are stored to know what it means). Bit shifts seem like they're only likely to be used by sophisticated users who don't need a safety net. 

With that said, if there are no spillovers in performance, no harm in offering (aside from all your developing time :)).
