### ISSUE TITLE
The documentation is not deployed

### ISSUE THREAD

**Issue by hyrodium** [JeffreySarnoff/SaferIntegers.jl#28]
http://jeffreysarnoff.github.io/SaferIntegers.jl/stable/ and http://jeffreysarnoff.github.io/SaferIntegers.jl/dev/ return 404.
This repository seems to be in the middle of a migration from travis to github actions. If this assumption is correct, I can make a PR to:

* remove `./.travis.yml`
* add `./.github/workflows/ci.yml` to run tests and deploy documentation

**Comment by JeffreySarnoff** [comment]
please do

**Comment by hyrodium** [comment]
@JeffreySarnoff 
The `gh-pages` branch was pushed, but https://jeffreysarnoff.github.io/SaferIntegers.jl/dev/ still shows 404.
Could you check the settings for GitHub Pages in https://github.com/JeffreySarnoff/SaferIntegers.jl/settings/pages ?

**Comment by JeffreySarnoff** [comment]
ok docs are linked https://jeffreysarnoff.github.io/SaferIntegers.jl/dev/

**Comment by JeffreySarnoff** [comment]
The setting had become unset.  I fixed this and bumped the patch level,
reregistering the repo to generate the docs.
Let me know ...

**Comment by hyrodium** [comment]
Is there any trouble with document deployment? https://jeffreysarnoff.github.io/SaferIntegers.jl/dev/ shows correctly but https://jeffreysarnoff.github.io/SaferIntegers.jl/stable/ does not. This can be solved by pushing tags such as `v1.2.3+doc1`. See https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documentation-Versions for more information.

**Comment by JeffreySarnoff** [comment]
Yes there is. And the same issue is happening in two other repositories.
I am out for the afternoon; then I will ask for help with this.
Thank you for letting me know!
