### ISSUE TITLE
ChangePrecision

### ISSUE THREAD

**Issue by JeffreySarnoff** [JeffreySarnoff/SaferIntegers.jl#8]
@stevengj As an experiment I included `ChangePrecision.jl` in `SaferIntegers.jl` by defining `tryparse`, importing `@changeprecision` and `changeprecision` then exporting `@changeprecision` and including https://github.com/JeffreySarnoff/SaferIntegers.jl/blob/master/src/change.jl which duplicates your source for that one function.  And it works, at least in the small:
```
julia> @changeprecision SafeInt16 begin
           x = 17
           y = 13
           z = divrem(x,y)
       end
(1, 4)

julia> typeof.(ans)
(SafeInt16, SafeInt16)
```

Is this an appropriate use of your package?  Is there more I need to do for it to work in this way robustly?

**Comment by stevengj** [comment]
ChangePrecision is designed for floating point types, so I think further modification would be needed to make it work well for integer code. You wouldn’t want it to touch floating point literals, for example.

**Comment by JeffreySarnoff** [comment]
replaced with @saferintegers
